### POST Request to create a new patient
POST http://localhost:4004/api/v1/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Moe Kafka7",
  "email": "kafka_test18@example1.com",
  "address": "123 Main St",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2023-01-01"
}